spring:
  application:
    name: test
  profiles:
    active:
    - dev
# security config
  security:
    user:
      name: user
      password: password
      roles:
      - ADMIN

# application info
info:
  creator: adhithyan

# actuator endpoints enable
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

# logging and pattern
logging:
  file: logs/app.log
  pattern:
#    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
#  level:
#    root: INFO
#    com:
#      test:
#        webservicedemo: ERROR
       
# log level enablement 
#debug: true
#trace: true

