spring:
  application:
    name: test
  profiles:
    active:
    - dev

  security:
    user:
      name: user
      password: password
      roles:
      - ADMIN


info:
  creator: adhithyan

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

logging:
  file: logs/app.log
  pattern:
#    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
#  level:
#    root: INFO
#    com:
#      test:
#        webservicedemo: ERROR
        
#debug: true
#trace: true

